volunteer_management_system_report_generation:
    resource: "@VolunteerManagementSystemReportGenerationBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_pages:
    resource: "@VolunteerManagementSystemPagesBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_styles:
    resource: "@VolunteerManagementSystemStylesBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_registration:
    resource: "@VolunteerManagementSystemRegistrationBundle/Resources/config/routing.yml"
    prefix:   /

