volunteer_management_system_workshop:
    resource: "@VolunteerManagementSystemWorkshopBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_stat:
    resource: "@VolunteerManagementSystemStatBundle/Resources/config/routing.yml"
    prefix:   /
volunteer_management_system_project:
    resource: "@VolunteerManagementSystemProjectBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_event:
    resource: "@VolunteerManagementSystemEventBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_news:
    resource: "@VolunteerManagementSystemNewsBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_notification:
    resource: "@VolunteerManagementSystemNotificationBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_report_generation:
    resource: "@VolunteerManagementSystemReportGenerationBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_pages:
    resource: "@VolunteerManagementSystemPagesBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_styles:
    resource: "@VolunteerManagementSystemStylesBundle/Resources/config/routing.yml"
    prefix:   /

volunteer_management_system_registration:
    resource: "@VolunteerManagementSystemRegistrationBundle/Resources/config/routing.yml"
    prefix:   /

