volunteer_management_system_report_generation_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: VolunteerManagementSystemReportGenerationBundle:Default:index }

_track_record:
    pattern: /TrackRecord
    defaults: { _controller: VolunteerManagementSystemReportGenerationBundle:TrackRecord:TrackRecord }

_track_record_initialize:
    pattern: /TrackRecordInitialize
    defaults: { _controller: VolunteerManagementSystemReportGenerationBundle:TrackRecord:InitializeTrackRecord }
    
_project_report:
    pattern: /ProjectReport
    defaults: { _controller: VolunteerManagementSystemReportGenerationBundle:ProjectReport:ProjectReport }