_track_record:
    pattern: /TrackRecord
    defaults: { _controller: VolunteerManagementSystemReportGenerationBundle:TrackRecord:TrackRecord }

_track_record_initialize:
    pattern: /TrackRecordInitialize
    defaults: { _controller: VolunteerManagementSystemReportGenerationBundle:TrackRecord:InitializeTrackRecord }
    
_project_report:
    pattern: /ProjectReport
    defaults: { _controller: VolunteerManagementSystemReportGenerationBundle:ProjectReport:ProjectReport }
    
_userDetails_display:
    pattern: /userDetailsDisplay
    defaults: { _controller: VolunteerManagementSystemReportGenerationBundle:userDetailsDisplay:formdisplay }
