parameters:
#    volunteer_management_system_report_generation.example.class: VolunteerManagementSystem\ReportGenerationBundle\Example

services:
#    volunteer_management_system_report_generation.example:
#        class: %volunteer_management_system_report_generation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
