
projectcreation:
    pattern: /projectcreation
    defaults: { _controller: VolunteerManagementSystemProjectBundle:ProjectCreation:projectcreation }

projectsubmission:
    pattern: /projectsubmission
    defaults: { _controller: VolunteerManagementSystemProjectBundle:ProjectSubmission:projectsubmission }

projectconfirmation:
    pattern: /projectconfirmation
    defaults: { _controller: VolunteerManagementSystemProjectBundle:ProjectConfirmation:projectconfirmation }

projectview:
    pattern: /project_view
    defaults: { _controller: VolunteerManagementSystemProjectBundle:ProjectView:projectview }
