parameters:
#    volunteer_management_system_project.example.class: VolunteerManagementSystem\ProjectBundle\Example

services:
#    volunteer_management_system_project.example:
#        class: %volunteer_management_system_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
