create_event:
    pattern:  /create_event
    defaults: { _controller: VolunteerManagementSystemEventBundle:CreateEvent:createEvent }
save_event:
    pattern:  /save_event
    defaults: { _controller: VolunteerManagementSystemEventBundle:CreateEvent:eventSave }
view_event:
    pattern:  /view_event
    defaults: { _controller: VolunteerManagementSystemEventBundle:ViewEvent:viewEvent }
register_event:
    pattern:  /register_event
    defaults: { _controller: VolunteerManagementSystemEventBundle:RegisterEvent:register }
close_event:
    pattern:  /close_event
    defaults: { _controller: VolunteerManagementSystemEventBundle:CloseEvent:close }
finished_event:
    pattern:  /finished_event
    defaults: { _controller: VolunteerManagementSystemEventBundle:CloseEvent:finished }
