account_register:
   pattern:  /register
   defaults: { _controller: VolunteerManagementSystemRegistrationBundle:Registration:register }

account_create:
   pattern:  /register/create
   defaults: { _controller: VolunteerManagementSystemRegistrationBundle:Submission:submission }

welcome:
   pattern: /homepage
   defaults: { _controller: VolunteerManagementSystemRegistrationBundle:Homepage:welcome }