<?php

namespace VolunteerManagementSystem\ReportGenerationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrackRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRecordRepository extends EntityRepository
{
}
